feat(src/build/ci): bumped libs to 7495e15 (falco 0.32.2 loader); add driver base image to reduce runtime image sizes; fix stop condition for traversing process tree, which could lead to infinite loop and memory leak in the updated version of the libs
Signed-off-by: Frederico Araujo <frederico.araujo@ibm.com>

diff --git a/scripts/service/bin/sysflow b/scripts/service/bin/sysflow
--- a/scripts/service/bin/sysflow
+++ b/scripts/service/bin/sysflow
@@ -5,7 +5,7 @@ SYSFLOW=/usr/lib/systemd/system/sysflow.service
 SFPROCESSOR=/usr/lib/systemd/system/sysflow-processor.service
 SFCOLLECTOR=/usr/lib/systemd/system/sysflow-collector.service
 DKMS=/etc/sysflow/modules/src/dkms
-MAKE=/etc/sysflow/modules/bin/make
+MAKE=make
 
 status () {
     systemctl status "sysflow*"
@@ -17,6 +17,10 @@ start () {
     fi
     if ! command -v dkms &> /dev/null; then 
         echo "dkms not found, installing..."
+        if ! command -v $MAKE &> /dev/null; then
+            echo "make not found, trying to use prepackaged make binary..."
+            MAKE=/etc/sysflow/modules/bin/make
+        fi
         if [ "$(grep -Ei 'debian|buntu|mint' /etc/*release)" ]; then
             $MAKE -C $DKMS install-debian
         elif [ "$(grep -Ei 'fedora|redhat|cent' /etc/*release)" ]; then
